# ╭────────────────────────────────────────────sushi-config.yaml───────────────────────────────────────────────╮
# | documentation of this sushi-config.yaml file https://fshschool.org/docs/sushi/configuration/               |
# ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

id: ihe.pharm.meow
canonical: http://profiles.ihe.net/PHARM/MEOW
name: IHE_PHARM_MEOW
version: 0.1.0
fhirVersion: 5.0.0
status: active
title: "IHE Pharmacy Medication Overview"
description: ImplementationGuide for IHE Pharmacy Medication Overview
copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2022+
releaseLabel: ci-build
#releaseLabel: Trial-Implementation
#date: 2022-03-01
publisher:
  name: Integrating the Healthcare Enterprise (IHE)
  url: http://ihe.net
  email: secretary@ihe.net
contact:
  - name: Jose Costa Teixeira
    telecom:
      - system: email
        value: jose.a.teixeira@gmail.com
        use: work
license: CC-BY-SA-4.0
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#dependencies:
#  https://profiles.ihe.net/fhir/ihe.formatcode.fhir: 0.2.4
 
parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
  path-pages:
    - input/pagecontent
    - fsh-generated/includes
 # active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  #apply-publisher: 'true'
  apply-version: 'true'
  #show-inherited-invariants: 'false'
  usage-stats-opt-out: 'true'
  autoload-resources: 'true'
  #shownav: 'true'

# additional examples that need descriptions
#resources:
#  Bundle/Bundle-FindDocumentReferences:
#    name: Example FindDocumentReferences response
#    description: An example of a searchset Bundle with one DocumentReference
#    exampleBoolean: true
# ╭────────────────────────────────────────────pages───────────────────────────────────────────────╮
# │  The pages property corresponds to IG.definition.page.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
pages:
  index.md:
    title: "MeOw Home"
  1330_overview.md:
    title: "1:33.0 Overview"
  functional-updates.md:
    title: "Functional Updates"
  glossary.md:
    title: "Glossary"
  1331_actors_and_transactions.md:
    title: "1:33.1 Actors and Transactions"
  1332_actor_options.md:
    title: "1:33.2 Actor Options"
#  1333_required_grouping.md:
#    title: "1:33.3 Required Grouping"

  1335_security_considerations.md:
    title: "1:33.5 Security Considerations"
  1336_cross_profile_considerations.md:
    title: "1:33.6 Cross Profile Considerations"
  PHARM-x.md:
    title: "PHARM xxx"
  PHARM-y.md:
    title: "PHARM yyy"
#  ITI-66.md:
#    title: "2:3.66 Find Document Lists [ITI-66]"
#  ITI-67.md:
#    title: "2:3.67 Find Document References [ITI-67]"
#  ITI-68.md:
#    title: "2:3.68 Retrieve Document [ITI-68]"
  32_fhir_maps.md:
    title: "3:4.5 FHIR Maps"
  testplan.md:
    title: "Test Plan"
#    extension: 
#      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
#        valueCode: informative
#  a_issues.md:
#    title: "Issues"
#    extension: 
#      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
#        valueCode: informative
      

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  MEOw Home: index.html
  Volume 1: 
    "Overview": 1330_overview.html
    "Actors and Transactions": 1331_actors_and_transactions.html
    "Actor Options": 1332_actor_options.html
   # "Actor Required Grouping": 1333_required_grouping.html
    "Security Considerations": 1335_security_considerations.html
    "Cross Profile Considerations": 1336_cross_profile_considerations.html
  Volume 2:
    "Transaction 1xxx": PHARM-x.html
  #  "Find Document Lists [ITI-66]": ITI-66.html
  #  "Find Document References [ITI-67]": ITI-67.html
  #  "Retrieve Document [ITI-68]": ITI-68.html
  Volume 3:
    "Error Codes": 31_xds.html
    "FHIR Maps": 32_fhir_maps.html
  Test Plan: testplan.html
  Artifact Index: artifacts.html
